sudo: required

services:
  - docker

script:
  - sh build.sh

deploy:
  provider: s3
  access_key_id:
    secure: Au2AO0rLJYA7E/X14Of3lmZvMFwiuyAGJW1oBsaDrNKcfQnIFvl4+GhpPJFC6YIv9/RNXtfajH8Ac+lyqItIfV/7i08QHoXXcjuPt2GooiepTwAQD49c16rUOELf93uE9nJK8P0mAaL8rjWzqTdOOcjm8ZoU2rl0zG0YZOUloXCsBdAg74/WrH+Bw7rtwCdbcoJMtzyFD1aYkyCW4KWk6/rrWbMRnbx56kIJ6gpuTi0cnOW/ovx3jZ62Hrhez2h6caVVfzB4TAOl855dOes8BhAK0DHO+aLdXS599Mthhf+om1s6ye4iKes6aoXKKzaPO/UxJlGX1Dy8iKTjqmXleno0sQ4r+XBcM06pX9W6RmW36HY+xQU9QzN+mihhDsOXgrFJ/biJxITJtv7/AIVTOLztrAD9yY4Ya+M30FNSpejMLNFrVZKn3cXTbAUc1Pzcu0vaUQ17z5/XIPn+12lYxcf8JnJ01xqhRBelujaUaAzRnn5oaNBVlpTgVo+7WiBlOs+r3BhLKbByDAZzGyr1fOO0MVNQB0ADws8Q8YDiI8mDC9i0LMGwHRR/E7AXSYlWI+eTMemD9WYFlU93DjhVZpvpgErJkUSp0BvOna9CRKfnKOVrAiCe25ikmdNfiA+vuhC66/SWSG0pZi1eacq4sm+S08tr4ZRe2bqMEttaDzw=
  secret_access_key:
    secure: KykiwYSSFhzAfDgtx4GJCqezpNGrRZsh7skBOuKxUTuXXsct0rGiRJyzPmckn7hjjFafE50UpYGD+7zemRkKwXYH1oDMcjSTl7qAWypztp2K6ogo5yCPAZ1GvzB0+Jox8vAPKjcr+ZViReBNUGegV7eVAPZO2725QvjfFkaVWCRteiiMx5F/KVu+ZbxJImsmAbliXtOIaO3A+TtoGUQuSeXhsNKZBmUiKMFN4nqDT4Ut0S7CxLjNa7+v/EnK5f/jZfUgqrQTCxkKt1JAcFjxbzaOaECGBRmAfJ6UwASpJ/NlmgYBjRMgtWvLDy03Ha/pZEYyDEZPmCb2rs2nVQiRcrWp0HC5gLQrLc1arlaEvJplqaH1niQA1+GiUw1tDG/T5nbA8GEt1m5Oy3b1en92DT9i7DI2NyajRAMbv+aRaPA8zeivm5hBjQsoSIKlDYExJ9+YiLm4OZ+peok0g3Hn+EHXrOEIOKvZj72WkD3FxkwH2Vmes0twQyRON2PvYfY2H7i9mOyxt/M1mjfLFtRjjDC9JJ2Tp5JOcPIv2RzloHppxM4LSNw3k+qg+HSGkiPhL48X72W897R5xfUYWh1a+vrDzWjfZ3/BjgSz9IJDst0vCTkfiCHTVQlQ2c5/j4WRWzvFw4RYdjuIQRt1Z6mP4KyqUCbFcIrgsju4Eh6q4jc=
  bucket:
    secure: qG+nwdtkySI1Zh100jxv2WcJavtzqe4i6WFP59XqjrVR2VfIaPa2xDLg0zwqZIuH51D02Ky8NcBgb26nkurupIcAiTayGlTQoPBbtzxbzmk54GhuTFs4LbWHxk22ZTCNyxpzISLREyZidSztaSKQMTxsg3KAkOmoStdQCW1QwJEP+nlPoczGRN7KITr2A/nNI+693u9f4d3l5owyiKhH6bfpSv8/kydhdOHwp67KWynGK9O9H31PLX12xRrsQztBnP135ZSSrpEBBlz4SONvXHBDT9DgTvX7gEVK5IFVNzxET64fWE4UTWPNUxOfK1bdjCVy5HHjzmilO3nhCoDzPNWlE0uULUEGj0Hisoc2qxzFfp71WQBGIW0q/NpCfjBVNFVKdHMQDLQIoS3qFpZJtZiJpkYhGc2Qd+oIi19dH5cfkoCs6GQUijNTXC1NNPhiixfpDCaExgMIxjFcNYxkUNIvEr8YhMRhZVLGFT+tJa2nsLMT9pg4wFFe+DsaYSmAzxoWzhQG3TuVRvotGLtW5iHcfxtx2VZ3LU9deUXXlol1+tDWKs9nlHqYtJT8qokn1M0m0+JnDBjn0hYxjvM9rvpVUqm5LyfYi/dDq7C8uqZTSkEhIY3u3uElgXoUB8sj+Ldx0kqoj/rFRxLwrR2OBiuoAxYNZb0hEix1gn9gzBQ=
  region: eu-west-1
  local-dir: target/site
  upload-dir: poacc/billing/3.0
  acl: public_read
  skip_cleanup: true
  on:
    repo: OpenPEPPOL/peppol-bis-invoice-3
    branch: master
